name: Solution Package Validations

on: 
  pull_request:
    branches:
      - master
    paths:
      - 'Solutions/**/Package/mainTemplate.json'
      - 'Solutions/**/Package/createUiDefinition.json'

    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  Run-ExtractContent:
    name: Solution Package UI Testing - Testim.io
    runs-on: ubuntu-latest
    steps:
      - name: Chekout pull request braanch
        uses: actions/checkout@v3
        with:
            ref: ${{github.event.pull_request.head.ref}}
            repository: ${{github.event.pull_request.head.repo.full_name}}
            # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup git config
        run: |
              git config --local user.name "github-actions[bot]"
              git config --local user.email "<>"
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install python-dotenv
            pip install requests
      - name: Run Solution Package Validation Test
        env:
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
        run: |
            filePath=".script/tests/solutionPackageValidation/solutionPackageUIValidation.py"
            python $filePath
      # - name: Run Testim
      #   env:
      #     SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      #     WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
      #     USERNAME: ${{ vars.USERNAME }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #     TESTIM_API_KEY: ${{ secrets.TESTIM_API_KEY }}
      #   run: |
      #       filePath=".script/tests/solutionPackageValidation/runUITests.py"
      #       python $filePath
