name: Solution Package Validations

on: 
  pull_request:
    branches:
      - master
    paths:
      - 'Solutions/**/Package/mainTemplate.json'
      - 'Solutions/**/Package/createUiDefinition.json'

    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:


jobs:
  Run-SolutionPackage-Validation:
    name: Solution Package UI Testing - Testim.io
    runs-on: ubuntu-latest
    steps:
      - name: Chekout pull request braanch
        uses: actions/checkout@v2
        with:
          # persist-credentials: false 
          fetch-depth: 0


      - name: Get Modified Files
        run: |
          git fetch origin master:refs/remotes/origin/master
          git diff --name-only origin/master ${{ github.events.pull_request.head.sha }}/../../../Solutions/ > changedFiles.txt
          echo "CHANGED_FILES = $(cat changedFiles.txt)" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install os
              pip install dotenv
      - name: Run Script
        run: |
          python run.py  
