name: Solution Package Validations
permissions:
  contents: write
on: 
  pull_request:
    branches:
      - master
    paths:
      - 'Solutions/**'
    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
  Run-SolutionPackage-Validation:
    name: Solution Package UI Testing - Testim.io
    runs-on: ubuntu-latest
    steps:
      - name: Chekout pull request braanch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Get Modified Files
        run: |
          git fetch origin master:refs/remotes/origin/master
          git diff --name-only origin/master ${{ github.events.pull_request.head.sha }} > changed_files.txt
          echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_ENV
          cat changed_files.txt